// <auto-generated />
using System;
using GrotixBackend.Telemetry.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Grotix.Persistence.Telemetry.GrotixBackend.Telemetry.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260527151354_SyncTelemetryModel")]
    partial class SyncTelemetryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrotixBackend.Telemetry.Domain.Model.Entities.ActiveThreshold", b =>
                {
                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.Property<string>("SensorType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sensor_type");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.HasKey("ZoneId", "SensorType");

                    b.ToTable("active_thresholds", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.Telemetry.Domain.Model.Entities.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<double?>("MaxPhysical")
                        .HasColumnType("double precision")
                        .HasColumnName("max_physical");

                    b.Property<double?>("MinPhysical")
                        .HasColumnType("double precision")
                        .HasColumnName("min_physical");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("sensor", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.Telemetry.Domain.Model.Entities.SensorReading", b =>
                {
                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("sensor_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("SensorId", "Timestamp");

                    b.ToTable("sensor_reading", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.Telemetry.Domain.Model.Entities.ThresholdBreachTracker", b =>
                {
                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("sensor_id");

                    b.Property<int>("ConsecutiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_count");

                    b.Property<DateTime?>("LastEvaluatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_evaluated_at");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sensor_type");

                    b.HasKey("ZoneId", "SensorId");

                    b.ToTable("threshold_breach_tracker", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
