// <auto-generated />
using System;
using GrotixBackend.Telemetry.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrotixBackend.Telemetry.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    partial class TelemetryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrotixBackend.Telemetry.Domain.Model.Entities.ActiveThreshold", b =>
                {
                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.Property<string>("SensorType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sensor_type");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.HasKey("ZoneId", "SensorType");

                    b.ToTable("active_thresholds", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.Telemetry.Domain.Model.Entities.ActuatorLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<int>("ActuatorId")
                        .HasColumnType("integer")
                        .HasColumnName("actuator_id");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<float?>("FlowRate")
                        .HasColumnType("real")
                        .HasColumnName("flow_rate");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ActuatorId", "Timestamp")
                        .HasDatabaseName("IX_actuator_log_actuator_id_timestamp");

                    b.ToTable("actuator_log", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.Telemetry.Domain.Model.Entities.AlertRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BreachDirection")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("breach_direction");

                    b.Property<double>("BreachedThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("breached_threshold");

                    b.Property<double>("MaxThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("max_threshold");

                    b.Property<double>("MinThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("min_threshold");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("sensor_id");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sensor_type");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("triggered_at");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId", "TriggeredAt")
                        .HasDatabaseName("IX_alert_log_zone_id_triggered_at");

                    b.ToTable("alert_log", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.Telemetry.Domain.Model.Entities.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<double?>("MaxPhysical")
                        .HasColumnType("double precision")
                        .HasColumnName("max_physical");

                    b.Property<double?>("MinPhysical")
                        .HasColumnType("double precision")
                        .HasColumnName("min_physical");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("sensor", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.Telemetry.Domain.Model.Entities.SensorReading", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.Property<double>("HumidityAir")
                        .HasColumnType("double precision")
                        .HasColumnName("humidity_air");

                    b.Property<double>("HumiditySoil")
                        .HasColumnType("double precision")
                        .HasColumnName("humidity_soil");

                    b.Property<double>("LightIntensity")
                        .HasColumnType("double precision")
                        .HasColumnName("light_intensity");

                    b.HasKey("DeviceId", "Timestamp");

                    b.HasIndex("ZoneId", "Timestamp")
                        .HasDatabaseName("IX_sensor_reading_zone_id_timestamp");

                    b.ToTable("sensor_reading", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.Telemetry.Domain.Model.Entities.ThresholdBreachTracker", b =>
                {
                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("sensor_id");

                    b.Property<int>("ConsecutiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_count");

                    b.Property<DateTime?>("LastEvaluatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_evaluated_at");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sensor_type");

                    b.HasKey("ZoneId", "SensorId");

                    b.ToTable("threshold_breach_tracker", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
