// <auto-generated />
using System;
using GrotixBackend.HardwareDevice.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grotix.Persistence.HardwareDevice.GrotixBackend.HardwareDevice.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(HardwareDeviceDbContext))]
    [Migration("20260527151328_SyncHardwareDeviceModel")]
    partial class SyncHardwareDeviceModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GrotixBackend.HardwareDevice.Domain.Model.Aggregates.DeviceActuator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActuatorID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CurrentState")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MicrocontrollerId")
                        .HasColumnType("int")
                        .HasColumnName("MicrocontrollerID");

                    b.Property<int>("Pin")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("MicrocontrollerId");

                    b.ToTable("actuator", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.HardwareDevice.Domain.Model.Aggregates.DeviceSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SensorID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("MaxPhysical")
                        .HasColumnType("double");

                    b.Property<int>("MicrocontrollerId")
                        .HasColumnType("int")
                        .HasColumnName("MicrocontrollerID");

                    b.Property<double?>("MinPhysical")
                        .HasColumnType("double");

                    b.Property<int>("Pin")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("ZoneID");

                    b.HasKey("Id");

                    b.HasIndex("MicrocontrollerId");

                    b.ToTable("sensor", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.HardwareDevice.Domain.Model.Aggregates.Microcontroller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MicrocontrollerID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatteryLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int?>("SignalStrength")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("ZoneID");

                    b.HasKey("Id");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("microcontroller", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
