// <auto-generated />
using System;
using GrotixBackend.IrrigationCycle.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grotix.Persistence.IrrigationCycle.GrotixBackend.IrrigationCycle.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(IrrigationCycleDbContext))]
    [Migration("20260527151347_SyncIrrigationCycleModel")]
    partial class SyncIrrigationCycleModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GrotixBackend.IrrigationCycle.Domain.Model.Aggregates.IrrigationCycleRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CycleID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbortReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<double>("VolumeLiters")
                        .HasColumnType("double");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("ZoneID");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.HasIndex("ZoneId", "Status");

                    b.ToTable("irrigation_cycle", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.IrrigationCycle.Domain.Model.Aggregates.IrrigationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DaysOfTheWeek")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("ZoneID");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("irrigation_schedule", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
