// <auto-generated />
using GrotixBackend.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrotixBackend.IAM.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(IamDbContext))]
    [Migration("20260526235900_InitialIamContext")]
    partial class InitialIamContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GrotixBackend.IAM.Domain.Model.Aggregates.Identity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdentityID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("identity", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.IAM.Domain.Model.Aggregates.Identity", b =>
                {
                    b.OwnsOne("GrotixBackend.IAM.Domain.Model.ValueObjects.PasswordHash", "HashedPassword", b1 =>
                        {
                            b1.Property<int>("IdentityId")
                                .HasColumnType("int");

                            b1.Property<string>("HashedValue")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("IdentityId");

                            b1.ToTable("identity");

                            b1.WithOwner()
                                .HasForeignKey("IdentityId");
                        });

                    b.Navigation("HashedPassword")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
