// <auto-generated />
using System;
using GrotixBackend.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrotixBackend.CultivationArea.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(CultivationAreaDbContext))]
    partial class CultivationAreaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GrotixBackend.CultivationArea.Domain.Model.Aggregates.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CropID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("ImageURL");

                    b.Property<int>("MaxStressTime")
                        .HasColumnType("int");

                    b.Property<double>("OptimalHumidityAir")
                        .HasColumnType("double");

                    b.Property<double>("OptimalHumiditySoil")
                        .HasColumnType("double");

                    b.Property<double>("OptimalLight")
                        .HasColumnType("double");

                    b.Property<double>("OptimalTemperature")
                        .HasColumnType("double");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("CommonName")
                        .IsUnique();

                    b.HasIndex("ScientificName")
                        .IsUnique();

                    b.ToTable("crop", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.CultivationArea.Domain.Model.Aggregates.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FarmID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociationId")
                        .HasColumnType("int")
                        .HasColumnName("AssociationID");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.HasIndex("AssociationId", "Name")
                        .IsUnique();

                    b.ToTable("farm", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.CultivationArea.Domain.Model.Aggregates.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ZoneID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CropId")
                        .HasColumnType("int")
                        .HasColumnName("CropID");

                    b.Property<string>("CurrentPhase")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("FarmId")
                        .HasColumnType("int")
                        .HasColumnName("FarmID");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("IrrigationMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime?>("PhaseStartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("FarmId");

                    b.ToTable("zone", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.CultivationArea.Domain.Model.Aggregates.ZoneMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ZoneMemberID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("AssignedAt");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("AssignedByUserID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("ZoneID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ZoneId", "UserId")
                        .IsUnique();

                    b.ToTable("zone_member", (string)null);
                });

            modelBuilder.Entity("GrotixBackend.CultivationArea.Domain.Model.Aggregates.Zone", b =>
                {
                    b.HasOne("GrotixBackend.CultivationArea.Domain.Model.Aggregates.Crop", null)
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrotixBackend.CultivationArea.Domain.Model.Aggregates.Farm", null)
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrotixBackend.CultivationArea.Domain.Model.Aggregates.ZoneMember", b =>
                {
                    b.HasOne("GrotixBackend.CultivationArea.Domain.Model.Aggregates.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
