<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\Grotix.Shared\Grotix.Shared.csproj" />
    <ProjectReference Include="..\Grotix.CultivationArea\Grotix.CultivationArea.csproj" />
    <ProjectReference Include="..\Grotix.Profiles\Grotix.Profiles.csproj" />
    <ProjectReference Include="..\Grotix.Contracts.Auth\Grotix.Contracts.Auth.csproj" />
    <ProjectReference Include="..\Grotix.Contracts.Profiles\Grotix.Contracts.Profiles.csproj" />
    <ProjectReference Include="..\Grotix.Contracts.Integration\Grotix.Contracts.Integration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="**\*.cs" />
    <Compile Include="..\..\Grotix\Telemetry\**\*.cs"
             Exclude="..\..\Grotix\Telemetry\Infrastructure\Persistence\**\*.cs;..\..\Grotix\Telemetry\Infrastructure\Repositories\**\*.cs;..\..\Grotix\Telemetry\Infrastructure\Integration\**\*.cs" />
  </ItemGroup>

</Project>
